"""empty message

Revision ID: 10c9e90e0d34
Revises: a30efa4528c6
Create Date: 2026-03-03 22:19:47.863615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c9e90e0d34'
down_revision: Union[str, Sequence[str], None] = 'a30efa4528c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('cover_url')
    )
    op.create_index(op.f('ix_album_ID'), 'album', ['ID'], unique=False)
    op.create_index(op.f('ix_album_title'), 'album', ['title'], unique=False)
    op.create_table('author',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('photo_url')
    )
    op.create_index(op.f('ix_author_ID'), 'author', ['ID'], unique=False)
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_table('user',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_verification', sa.Boolean(), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_user_ID'), 'user', ['ID'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('album_author',
    sa.Column('author_ID', sa.Integer(), nullable=True),
    sa.Column('album_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_ID'], ['album.ID'], ),
    sa.ForeignKeyConstraint(['author_ID'], ['author.ID'], )
    )
    op.create_table('playlist',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('cover_url')
    )
    op.create_index(op.f('ix_playlist_ID'), 'playlist', ['ID'], unique=False)
    op.create_table('profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('RUS', 'ENG', name='languages'), nullable=False),
    sa.Column('country', sa.Enum('RUS', 'KAZ', 'BLR', name='countries'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_profile_ID'), 'profile', ['ID'], unique=False)
    op.create_table('track',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('album_ID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['album_ID'], ['album.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('file_url')
    )
    op.create_index(op.f('ix_track_ID'), 'track', ['ID'], unique=False)
    op.create_index(op.f('ix_track_title'), 'track', ['title'], unique=False)
    op.create_table('album_track',
    sa.Column('album_ID', sa.Integer(), nullable=True),
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_ID'], ['album.ID'], ),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], )
    )
    op.create_table('favorites',
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('user_ID', 'track_ID')
    )
    op.create_table('listen_history',
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.Column('listened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('listening_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['user.ID'], )
    )
    op.create_table('playlist_track',
    sa.Column('playlist_ID', sa.Integer(), nullable=True),
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_ID'], ['playlist.ID'], ),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], )
    )
    op.create_table('track_artist',
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.Column('author_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_ID'], ['author.ID'], ),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_artist')
    op.drop_table('playlist_track')
    op.drop_table('listen_history')
    op.drop_table('favorites')
    op.drop_table('album_track')
    op.drop_index(op.f('ix_track_title'), table_name='track')
    op.drop_index(op.f('ix_track_ID'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_profile_ID'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_playlist_ID'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_table('album_author')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_ID'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_index(op.f('ix_author_ID'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_album_title'), table_name='album')
    op.drop_index(op.f('ix_album_ID'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
