"""empty message

Revision ID: 225624493316
Revises: 10c9e90e0d34
Create Date: 2026-03-03 22:40:59.522423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225624493316'
down_revision: Union[str, Sequence[str], None] = '10c9e90e0d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'user_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'track_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'track_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'user_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
