"""empty message

Revision ID: 42fa075fb02d
Revises: b69f09d116d5
Create Date: 2025-10-11 22:37:17.537292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fa075fb02d'
down_revision: Union[str, Sequence[str], None] = 'b69f09d116d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'album_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'album_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
