"""empty message

Revision ID: 81aa82e888e4
Revises: f646348a63ea
Create Date: 2025-10-20 19:57:28.332825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81aa82e888e4'
down_revision: Union[str, Sequence[str], None] = 'f646348a63ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_track', sa.Column('playlist_ID', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('playlist_track_playlist_ID _fkey'), 'playlist_track', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_track', 'playlist', ['playlist_ID'], ['ID'])
    op.drop_column('playlist_track', 'playlist_ID ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_track', sa.Column('playlist_ID ', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'playlist_track', type_='foreignkey')
    op.create_foreign_key(op.f('playlist_track_playlist_ID _fkey'), 'playlist_track', 'playlist', ['playlist_ID '], ['ID'])
    op.drop_column('playlist_track', 'playlist_ID')
    # ### end Alembic commands ###
