"""first migration

Revision ID: 849f0e8a17e2
Revises: 
Create Date: 2025-09-28 14:25:37.165391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849f0e8a17e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('cover_url')
    )
    op.create_index(op.f('ix_album_ID'), 'album', ['ID'], unique=False)
    op.create_index(op.f('ix_album_title'), 'album', ['title'], unique=False)
    op.create_table('author',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('photo_url')
    )
    op.create_index(op.f('ix_author_ID'), 'author', ['ID'], unique=False)
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_table('track',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('file_url')
    )
    op.create_index(op.f('ix_track_ID'), 'track', ['ID'], unique=False)
    op.create_index(op.f('ix_track_title'), 'track', ['title'], unique=False)
    op.create_table('user',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_verification', sa.Boolean(), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_user_ID'), 'user', ['ID'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('Album_Author',
    sa.Column('author_ID', sa.Integer(), nullable=True),
    sa.Column('album_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_ID'], ['album.ID'], ),
    sa.ForeignKeyConstraint(['author_ID'], ['author.ID'], )
    )
    op.create_table('Album_Track',
    sa.Column('album_ID', sa.Integer(), nullable=True),
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_ID'], ['album.ID'], ),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], )
    )
    op.create_table('Listen_History',
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.Column('listened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('listening_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['user.ID'], )
    )
    op.create_table('Track_Artist',
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.Column('author_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_ID'], ['author.ID'], ),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], )
    )
    op.create_table('favorites',
    sa.Column('user_ID', sa.Integer(), nullable=True),
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['user.ID'], )
    )
    op.create_table('playlist',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('cover_url')
    )
    op.create_index(op.f('ix_playlist_ID'), 'playlist', ['ID'], unique=False)
    op.create_table('Playlist_Track',
    sa.Column('playlist_ID ', sa.Integer(), nullable=True),
    sa.Column('track_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_ID '], ['playlist.ID'], ),
    sa.ForeignKeyConstraint(['track_ID'], ['track.ID'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Playlist_Track')
    op.drop_index(op.f('ix_playlist_ID'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_table('favorites')
    op.drop_table('Track_Artist')
    op.drop_table('Listen_History')
    op.drop_table('Album_Track')
    op.drop_table('Album_Author')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_ID'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_track_title'), table_name='track')
    op.drop_index(op.f('ix_track_ID'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_index(op.f('ix_author_ID'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_album_title'), table_name='album')
    op.drop_index(op.f('ix_album_ID'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
