"""empty message

Revision ID: 992a8212dbf8
Revises: 4e8bbe4b20d6
Create Date: 2026-03-03 21:53:07.892933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '992a8212dbf8'
down_revision: Union[str, Sequence[str], None] = '4e8bbe4b20d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pgbench_tellers')
    op.drop_table('pgbench_branches')
    op.drop_table('pgbench_history')
    op.drop_table('pgbench_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgbench_accounts',
    sa.Column('aid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=84), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('aid', name=op.f('pgbench_accounts_pkey'))
    )
    op.create_table('pgbench_history',
    sa.Column('tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=22), autoincrement=False, nullable=True)
    )
    op.create_table('pgbench_branches',
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bbalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=88), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bid', name=op.f('pgbench_branches_pkey'))
    )
    op.create_table('pgbench_tellers',
    sa.Column('tid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tbalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=84), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tid', name=op.f('pgbench_tellers_pkey'))
    )
    # ### end Alembic commands ###
