"""Add album_ID field into Track

Revision ID: b69f09d116d5
Revises: f4fb46936aeb
Create Date: 2025-10-11 22:25:58.642157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69f09d116d5'
down_revision: Union[str, Sequence[str], None] = 'f4fb46936aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('album_ID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'track', 'album', ['album_ID'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.drop_column('track', 'album_ID')
    # ### end Alembic commands ###
