"""Add cascde delete

Revision ID: d07c6bcfc9d6
Revises: f6b2dbfda4ca
Create Date: 2025-10-11 21:49:46.699686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07c6bcfc9d6'
down_revision: Union[str, Sequence[str], None] = 'f6b2dbfda4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
