"""empty message

Revision ID: d2c0736eaac1
Revises: 2bdd2a1b75ab
Create Date: 2025-10-12 16:25:45.756080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c0736eaac1'
down_revision: Union[str, Sequence[str], None] = '2bdd2a1b75ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'favorites', ['track_ID'])
    op.create_unique_constraint(None, 'favorites', ['user_ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='unique')
    op.drop_constraint(None, 'favorites', type_='unique')
    # ### end Alembic commands ###
