"""empty message

Revision ID: f646348a63ea
Revises: d2c0736eaac1
Create Date: 2025-10-12 16:30:50.276444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f646348a63ea'
down_revision: Union[str, Sequence[str], None] = 'd2c0736eaac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('favorites_track_ID_key'), 'favorites', type_='unique')
    op.drop_constraint(op.f('favorites_user_ID_key'), 'favorites', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('favorites_user_ID_key'), 'favorites', ['user_ID'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('favorites_track_ID_key'), 'favorites', ['track_ID'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
