"""empty message

Revision ID: f8f5d094bd8f
Revises: fb41a3118ecd
Create Date: 2026-03-03 21:57:22.609401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f5d094bd8f'
down_revision: Union[str, Sequence[str], None] = 'fb41a3118ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('RUS', 'ENG', name='languages'), nullable=False),
    sa.Column('country', sa.Enum('RUS', 'KAZ', 'BLR', name='countries'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_profile_ID'), 'profile', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_ID'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
